### ISSUE TITLE
Fails to handle error correctly if Google Play outdated

### ISSUE THREAD

**Issue by grassick** [dpa99c/cordova-plugin-request-location-accuracy#10]
If Google Play Services is outdated, it crashes as follows:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(org.json.JSONObject)' on a null object reference
tat cordova.plugin.RequestLocationAccuracy.handleError(RequestLocationAccuracy.java:216)
at cordova.plugin.RequestLocationAccuracy.onConnectionFailed(RequestLocationAccuracy.java:442)
```

Since context isn't set.

I notice that it will fail in the same way if it gets an exception making the request:

```
        }catch(Exception e ) {
            handleError(e.getMessage(), ERROR_EXCEPTION);
            result = false;
        }
```

Because it has not done a: `context = callbackContext;`

I'm getting tons of these crashes from our users, unfortunately. I suspect there is a lot of outdated Google Play Services out there.

**Comment by dpa99c** [comment]
Oops, thanks for pointing this out - stupid mistake on my part. I have to admit I'm not making much use of this plugin in production, so I hadn't spotted the problem.  I'll fix this and push out an update to npm ASAP.

Out of interest, what crash reporting system did you spot this in? The built-in Google Play Dev Console one?

**Comment by dpa99c** [comment]
Published to npm as v1.0.2

**Comment by grassick** [comment]
I'm worried that this won't solve it: `initialize` calls `buildGoogleApiClient` before a request is made, and thus before a context is available. If it can't connect, might `.addOnConnectionFailedListener(this)` be triggered immediately? In which case `context.error(error)` would still crash? Maybe there should be a check for null around the context.error part.

**Comment by dpa99c** [comment]
OK, commit b9fe8737f7ebed58ccdc3aa2dfcab7ee5f554d94 should cover all the edge cases. I've tested in an Android emulator instance that doesn't have Google Play Services present and it now handles the error without crashing. Pushed out as v1.0.3

**Comment by grassick** [comment]
Thanks! Much appreciated.
