### ISSUE TITLE
New iOS canRequest feature

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-request-location-accuracy#13]
Can Android and iOS requests be made from a single call function?  It seems they are separate features...like

```
if (iOS) {
   cordova.plugins.locationAccuracy.canRequest() ;
} else if (Android) {
   cordova.plugins.locationAccuracy.request(function (success){ ... }
}
```

Either that or possibly your documentation is inaccurate, because in the Android & iOS section, under iOS you first list:  
`cordova.plugins.locationAccuracy.request(successCallback, errorCallback)`

but then the very next iOS example usage shows:
`cordova.plugins.locationAccuracy.canRequest(function(canRequest){
    if(canRequest){ ...`

If Android/iOS can be done from same call, can you show an integrated example?

**Comment by rolinger** [comment]
Probably for a different topic....but is there any known method (have a hard time finding a universal method) that will allow you get a users location without GPS turned on?  I am reading about possibly retrieving "last known location" or trying to retrieve LOCATION_COARSE (which I believe uses wifi or tower location info).  Any comments would be appreciated.   I am trying to satisfy google maps initializing with 'some' form of known location (with GPS turned off) to center the map as accurately as possible....without any know location maps show up blank.

Some universal plugin of these additional options:  https://developer.android.com/training/location/retrieve-current.html

**Comment by dpa99c** [comment]
> Can Android and iOS requests be made from a single call function

Sorry, been really busy but will try to make some time for a cross-platform example/solution...

>  is there any known method (have a hard time finding a universal method) that will allow you get a users location without GPS turned on

Yes. Set `enableHighAccuracy: false` - [https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/#geolocationoptions](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-geolocation/#geolocationoptions)

**Comment by dpa99c** [comment]
v2.1.0 unifies the platforms to make a single cross-platform call possible. See the [updated documentation](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#combined-android--ios-example)
