### ISSUE TITLE
Plugin Conflict?

### ISSUE THREAD

**Issue by SteveFulton95** [dpa99c/cordova-plugin-request-location-accuracy#14]
When I have both cordova-plugin-fcm and cordova-plugin-request-location-accuracy plugins installed my build fails. Here is the output:

Found com.google.android.gms:play-services-location:+, but version 9.2.0 is needed for the google-services plugin.
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':processDebugGoogleServices'. > Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

When I have one or the other installed the build is successful.

**Comment by dpa99c** [comment]
This is covered by #8 and the [corresponding Firebase plugin issue](https://github.com/fechanique/cordova-plugin-fcm/issues/25)
