### ISSUE TITLE
Request on iOS

### ISSUE THREAD

**Issue by kaynz** [dpa99c/cordova-plugin-request-location-accuracy#15]
Hi,

if I request location on iOS and it has been granted earlier, the promise will be rejected with "Location services is already enabled". Why don't you resolve the promise since GPS is enabled?

@dpa99c

**Comment by elektray** [comment]
I'm having the same issue. Test on iOs 9.3 It took me 2 hours to figure out what was happening...
This plugin is very useful but until this issue is not fixed I will have to stick with switchToSettings()

**Comment by kaynz** [comment]
@dpa99c Thank you! :)

**Comment by dpa99c** [comment]
Will try to push this out in an npm release sometime tonight

**Comment by elektray** [comment]
Happy to help!

Thanks to you for your hard work.

**Comment by dpa99c** [comment]
v2.1.0 published to npm should resolve this

**Comment by elektray** [comment]
Awesome!
Thank you!
