### ISSUE TITLE
Is there any Android Compatibility Issues ?

### ISSUE THREAD

**Issue by dhavalkakkad** [dpa99c/cordova-plugin-request-location-accuracy#17]
Hi,

I am using this plugin for one of my cordova app, its working fine on 4.2+, not on 4.0 . Is there any min android version required ?

Thanks

**Comment by dpa99c** [comment]
This plugin requires Google Play Services v7 or higher. It was in v7 of the library that the Location APIs were added that this plugin makes use of. I haven't tested on Android 4.0, but it may either be that v7 of the library is not available on Android 4.0, or that you need to manually update the Google Play Services on this version of Android.

You can check what version of Google Play Services is installed on the device using the [Play Services Info](https://play.google.com/store/apps/details?id=com.weberdo.apps.serviceinfo&hl=en_GB) app

**Comment by dpa99c** [comment]
Reopen if still an issue
