### ISSUE TITLE
Success callback is not invoked, if request() just after the launch of app

### ISSUE THREAD

**Issue by rvdfox** [dpa99c/cordova-plugin-request-location-accuracy#18]
the success callback is not invoked if request() method is called just after the launch of app,its common for almost all Android devices,although if i give breakpoints or wait for few seconds after appearance of dialog then it works perfectly fine.

**Comment by dpa99c** [comment]
Are you waiting for the `deviceready` event before calling `request()`?

**Comment by dpa99c** [comment]
Reopen if still an issue

**Comment by rvdfox** [comment]
yes i am waiting for the deviceready() event, although i figured out what was happening, the success callback for the function request() is being called only once, (i m not sure but it might be cordova way),and next time when i invoke request method, it didnt performed same way
