### ISSUE TITLE
Handle Play Services Update

### ISSUE THREAD

**Issue by kaynz** [dpa99c/cordova-plugin-request-location-accuracy#19]
Hi,

I've got the following scenario on my device:

```
cordova.plugins.locationAccuracy.ERROR_GOOGLE_API_CONNECTION_FAILED
code:5
message: "Failed to connect to Google Play Services: The installed version of Google Play services is out of date."
```

Is there a way to open a question prompt and let the user decide wether to update play services?

**Comment by dpa99c** [comment]
You can implement such a mechanism by first displaying a dialog to the user asking if they want to update  Google Play Services using [cordova-plugin-dialogs](https://github.com/apache/cordova-plugin-dialogs). If they agree, use [cordova-plugin-market](https://github.com/xmartlabs/cordova-plugin-market) to launch the Play Store on the Play Services page, where the Update option will be visible:

```
cordova.plugins.market.open('com.google.android.gms');
```

**Comment by kaynz** [comment]
Wouldn't it be more elegant to use getErrorDialog() from Google Play Services?

**Comment by kaynz** [comment]
Great, thank you! 👍
