### ISSUE TITLE
Module has no exported member 'Location Accuracy'

### ISSUE THREAD

**Issue by junaidahmed93** [dpa99c/cordova-plugin-request-location-accuracy#20]
Hello everyone,
I am getting error while importing LocationAccuracy from ionic native
`Module has no exported member 'Location Accuracy'`
I have already installed the plugin.
Is there any solution?

**Comment by dpa99c** [comment]
The plugin is referenced via the `cordova.plugins.locationAccuracy` namespace. Please ensure you are using this to invoke the plugin. It would help if you could post the actual code you are using to call the plugin. Also see the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) for an illustration of how to use the plugin

**Comment by junaidahmed93** [comment]
Following this code snippet from IONIC 2 native

import { LocationAccuracy } from 'ionic-native';

LocationAccuracy.canRequest().then((canRequest: boolean) => {

  if(canRequest) {
    // the accuracy option will be ignored by iOS
    LocationAccuracy.request(LocaitonAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
      () => console.log('Request successful'),
      error => console.log('Error requesting location permissions', error)
    );
  }

});

**Comment by dpa99c** [comment]
This is not an issue with this plugin, but an issue with how to use the [typescript wrapper](https://github.com/driftyco/ionic-native/blob/master/src/plugins/location-accuracy.ts) created by the Ionic Native team to wrap this plugin. You should open an issue on [Ionic Native repo](https://github.com/driftyco/ionic-native/issues) regarding this.
