### ISSUE TITLE
cordova.plugins.locationAccuracy is not defined for iOS

### ISSUE THREAD

**Issue by peterchen16-zz** [dpa99c/cordova-plugin-request-location-accuracy#23]
When trying to run app on iOS, cordova.plugins.locationAccuracy is not defined, it used to work on iOS, then suddenly not working, I updated my iOS to version 9+, any idea is appreciated.

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) which [uses the plugin via the `cordova.plugins.locationAccuracy` namespace](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/ios/js/index.js#L13) and has been tested and verified as working on iOS 8, 9 and 10.

**Comment by dpa99c** [comment]
Reopen if still an issue
