### ISSUE TITLE
Error when calling location Accuracy request

### ISSUE THREAD

**Issue by peterchen16-zz** [dpa99c/cordova-plugin-request-location-accuracy#25]
I get this error recently when calling locationAccuracy.request

2, Value null at 0 of type org.json.JSONObject$1 cannot be converted to int

2 is the error code, I couldn't find any solution on the web

Any idea?

**Comment by dpa99c** [comment]
Please specify:

- What mobile platform (and version) are you encountering this on?
- What version of the plugin?
- What version of the Cordova platform?
- Are you able to reproduce it by building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example)?

**Comment by peterchen16-zz** [comment]
I am encountering this on all platform, sometimes it happens, sometimes it
doesn't.

I am using the latest version. I had the problem with version 1.3, then I
upgraded the version to 2.2.0, then the problem disappeared, and now it
happens again after one day.

I haven't test it on the example project yet.

Peter
ᐧ

**Comment by peterchen16-zz** [comment]
Correction, this only happens on all android platform

ᐧ

**Comment by peterchen16-zz** [comment]
iOS is working fine.
ᐧ

**Comment by peterchen16-zz** [comment]
The problem disappeared after I put
cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY in

Without it, only work on iOS
ᐧ

**Comment by piotr-cz** [comment]
Would be helpful if there would be message saying that the accurancy parameter is required
