### ISSUE TITLE
incompatibility google maps plugins native

### ISSUE THREAD

**Issue by gbelmm** [dpa99c/cordova-plugin-request-location-accuracy#26]
![captura de pantalla 2017-02-06 a las 17 19 16](https://cloud.githubusercontent.com/assets/731936/22664738/b6e9e8ca-ec90-11e6-856f-b0b3c2e5200e.png)

cordova-plugin-googlemaps 1.4.0 "phonegap-googlemaps-plugin
cordova-plugin-request-location-accuracy 2.2.0 "Request Location Accuracy"

help please!!!

**Comment by dpa99c** [comment]
The error shown in the screenshot is within the Google Maps plugin, so what has that got to do with this plugin?

**Comment by gbelmm** [comment]
When using this plugin gives me that error, if I remove it works perfect, any ideas?

**Comment by dpa99c** [comment]
This plugin uses the [unpinned/latest version of the Google Play Services Location library](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/plugin.xml#L32) whereas the Google Maps plugin [pins the version to v9.8.0](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L49) therefore you have a Gradle version conflict.

Version pinning in Cordova plugins is a bad idea for exactly this reason. You'll need to either edit the `plugin.xml` of the Google Maps plugin to unpin the version or edit the `plugin.xml` of this plugin to pin it to the same version (v9.8.0) as the Google Maps plugin. To do this, whichever plugin you modify will need to be first uninstalled from your project to remove the Gradle entries. You may also have to remove/re-add the Android platform to reset the Gradle files.

Then you'll need to either:

-  fork the Github repo, modify, commit, push and install it directly from there
- or clone the repo (or copy the folder from `plugins/`) to a folder outside the project, modify it, then install the plugin from the local path
