### ISSUE TITLE
Callback always returning error

### ISSUE THREAD

**Issue by gaurav-vachhani** [dpa99c/cordova-plugin-request-location-accuracy#27]
Plugin always returning `Accuracy request failed: error code=4` after accepting location Location Service.

**Comment by dpa99c** [comment]
This isn't enough information to determine if an issue exists, but from what little you have posted I'm guessing this is regarding the Android implementation?

The [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) is working fine on Android 7.1.1 with `cordova-plugin-request-location-accuracy@2.2.0` built with:

 - `cordova-android@6.1.2`
 - Google Play Services v39
 - Android Support Repository v44
 - Android Suppory Library v23.2.1
 
 
 Please try building and running the example project in your build environment. If you are able to reproduce the problem there, please post full details of the problem, including steps to reproduce, details of your build and runtime environments and if possible a code snippet or archived Cordova project which illustrates the problem.

**Comment by gaurav-vachhani** [comment]
I am using below code to update accuracy of  location but after accepting plugin is going to error function.

```
cordova.plugins.locationAccuracy.request(function (success){
    console.log("Successfully requested accuracy: "+success.message);
 }, function (error){
    console.error("Accuracy request failed: error code="+error.code+"; error message="+error.message);
    if(error.code !== cordova.plugins.locationAccuracy.ERROR_USER_DISAGREED){
        if(window.confirm("Failed to automatically set Location Mode to 'High Accuracy'. Would you like to switch to the Location Settings page and do this manually?")){
            cordova.plugins.diagnostic.switchToLocationSettings();
        }
    }
}, cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY);
```

**Comment by dpa99c** [comment]
Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) as it's a known working test case.

If you're able to reproduce the error with the example project app, please post the following details:

- Plugin version
- Cordova CLI version
- Cordova Android version
- Android SDK component versions
    - Google Play Services Library
    - Android Support Repository
    - Android Suppory Library
- Android version on test device
- Make/model of test device
