### ISSUE TITLE
Request only two options for permissions instead of 3 (see description)

### ISSUE THREAD

**Issue by kristopolous** [dpa99c/cordova-plugin-request-location-accuracy#28]
So this may be in the `switchToSettings()` ballpark, but on iOS, some apps give you the option of either completely denying location or having it on all the time - that's it.

Using this plugin with the switchToSettings, there's a third option, sorry if I am not getting the terminology right (I don't have the iphone in front of me), but it appears in the middle an is essentially "only when the app is running".

An example of an app that gives only two options is I believe facebook.  Is there a way to get this to only give those 2 options instead of the current 3?  Thanks!

**Comment by dpa99c** [comment]
The options that appear in the Settings app for location (Always or When In Use) are determined by whether either or both the related keys are included in the project .plist: `NSLocationWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription` - see [the Apple documentation](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18) for more.

Closing as this is unrelated to the functionality of this plugin.

**Comment by kristopolous** [comment]
Thanks. Sorry for the bad ticket.
