### ISSUE TITLE
RequestLocationAccuracy.java line 287

### ISSUE THREAD

**Issue by pooi-pooi** [dpa99c/cordova-plugin-request-location-accuracy#29]
Hello guys,
Im having a problem with `cordova-plugin-request-location-accuracy 2.2.0`

Looking on our Fabric, we got the following error:

```
RequestLocationAccuracy.java line 287
cordova.plugin.RequestLocationAccuracy.handleSuccess
```
on:
* MotoG3 (Android 6.0, 5.1.1)
* LG-H442 (Android 5.0.1)
* LG-K430 (Android 6.0)
* XT1078 (Android 6.0)

Full stack trace: [issue_2_crash_58E55B66025300014AB8903D4E93726E_a464d99a41864b0d89875eff7c5e9acf_0_v1.txt](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/files/902845/issue_2_crash_58E55B66025300014AB8903D4E93726E_a464d99a41864b0d89875eff7c5e9acf_0_v1.txt)

Google Play Services: 
![image](https://cloud.githubusercontent.com/assets/26969193/24759511/13c47b92-1abc-11e7-9d68-df2d3eec78da.png)

Do you know how to resolve that?
Thank you

**Comment by dpa99c** [comment]
Hi, thanks for the detailed info.

From it, I can see the problem: on [receiving a successful response from the permissions activity](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/src/android/RequestLocationAccuracy.java#L402), the success handler attempts to use the current context to invoke the JS callback ([line 287](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/src/android/RequestLocationAccuracy.java#L287). 

However, it's possible that Android can have killed the original Cordova activity when it switched to the permissions activity, make the context reference null.

I'll fix this with a simple "not null" check before attempting to invoke the callback context.

**Comment by dpa99c** [comment]
The fix has been released in a patch: `cordova-plugin-request-location-accuracy@2.2.1`
