### ISSUE TITLE
When there is no Google Play Services, `request` method is hanging

### ISSUE THREAD

**Issue by egesu** [dpa99c/cordova-plugin-request-location-accuracy#30]
It works as expected when there is play services installed and up-to-date. If it is not installed, I call `canRequest` method and it returns true - which I think should return false. Then I call `request` method but the success or error callback is not fired. I need to make a fallback way using diagnostics plugin but I cannot check if it works or not.

**Comment by dpa99c** [comment]
Closed for the same reason outlined in #31 - i.e. no intention to support Android devices without Google Play Services installed. Fork and modify if you see this as necessary.
