### ISSUE TITLE
Android runtime permission.

### ISSUE THREAD

**Issue by dielfilho-zz** [dpa99c/cordova-plugin-request-location-accuracy#33]
Is this working for android 6.0+?

**Comment by dpa99c** [comment]
Yes

**Comment by dielfilho-zz** [comment]
I'm having a problem because when I call the "canRequest" function using a device with android 6.0+ it does not show the permission dialog. Then I always get false as response.

**Comment by dpa99c** [comment]
On Android 6.0+ you must request run-time permission to use location before you can request an change in location accuracy mode with this plugin.

As documented, this plugin is designed to be used in conjunction with [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) so you should use [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization) and [isLocationAuthorized()](https://github.com/dpa99c/cordova-diagnostic-plugin#islocationauthorized) to check/request location permission, before attempting to request a change in accuracy.

The [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) gives [an example of how this can be done](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/android/js/index.js#L29).

**Comment by dielfilho-zz** [comment]
Thank you a lot! :+1:
