### ISSUE TITLE
cordova.plugins.locationAccuracy.request always error on android 4.4

### ISSUE THREAD

**Issue by Benoit-ROBIN** [dpa99c/cordova-plugin-request-location-accuracy#34]
Hi,

When I test my app on Android 4.4 (nexus 5), cordova.plugins.locationAccuracy.request always trigger catch error. 
My device have the last play store's version available on Android 4.4.
In config.xml I added  <preference name="android-minSdkVersion" value="19" />.
Is there something specific to add to make it works on Android 4.4 ?

My config : 
Cordova CLI: 7.0.1 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
OS: macOS Sierra
Node Version: v6.10.0
Xcode version: Xcode 8.3.3 Build version 8E3004b

**Comment by dpa99c** [comment]
Please try build and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) to rule out the possibility of bugs within your app code.

If the same issue occurs in the example app, please post details of the error message.

**Comment by dpa99c** [comment]
Closed due to no response from OP
