### ISSUE TITLE
Is there a way to request DEVICE_ONLY (GPS only) mode for location?

### ISSUE THREAD

**Issue by dhrytsenko** [dpa99c/cordova-plugin-request-location-accuracy#38]
Hi! It is not an issue, it is more a question. This plugin is nice. l wondering if exist a way to request DEVICE_ONLY mode if l want to use only GPS for location?

**Comment by dpa99c** [comment]
No, the Android [LocationRequest constants](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#constants) don't provide a DEVICE_ONLY constant.
