### ISSUE TITLE
errorCallback called even user agreed

### ISSUE THREAD

**Issue by jammy525** [dpa99c/cordova-plugin-request-location-accuracy#4]
errorCallback called even user agreed errror code is 4

**Comment by dpa99c** [comment]
With only that information to go on, there's not much chance of identifying a problem. 

What Android version does it happen on? Code snippet illustrating usage? Have you tried the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example)? Does that work OK?

Give some more useful information and I may be able to help

**Comment by jammy525** [comment]
> first of  all Many thanks for quick reply

i am using following code:
`function onRequestSuccess(success){
    console.log("Successfully requested accuracy: "+success.message);
}

function onRequestFailure(error){
    console.error("Accuracy request failed: error code="+error.code+"; error message="+error.message);
    if(error.code !== cordova.plugins.locationAccuracy.ERROR_USER_DISAGREED){
        if(window.confirm("Failed to automatically set Location Mode to 'High Accuracy'. Would you like to switch to the Location Settings page and do this manually?")){
            cordova.plugins.diagnostic.switchToLocationSettings();
        }
    }
}

cordova.plugins.locationAccuracy.request(onRequestSuccess, onRequestFailure, cordova.plugins.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY);`

for every case (agree or disagree) its onRequestFailure method is called and output is :Accuracy request failed: error code=4; error message=user disagree bla bla.although plugin working fine enable Location and wifi . but i need to closeapp in case of disagree.and dont want to enable wifi as well

**Comment by jammy525** [comment]
In addition to call onRequestFailure method. why it is asked to enable WI-FI ?

**Comment by dpa99c** [comment]
This plugin is just a very thin wrapper around the [Google Play Services Location API](http://developer.android.com/training/location/change-location-settings.html). It uses this API to make the request for the desired accuracy (in fact it's created based on [one of Google's own examples](https://github.com/googlesamples/android-play-location/blob/master/LocationSettings/app/src/main/java/com/google/android/gms/location/sample/locationsettings/MainActivity.java))

> why it is asked to enable WI-FI 

If you request an accuracy that entails using Network Provider as a location source (i.e. "High Accuracy" or "Battery Saving") then the Location Services API may ask you to enable Wifi for use in acquiring a location. Note that this is something that Google's library does, not this plugin.

I've tested the plugin via the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) on Android 4.4, 5.1 and 6.0 and it works fine on each of these.

While your use of the plugin looks fine to me, please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) to see if it works in the environment you're having problems with. If you're unable to build it for some reason, there's a [pre-built APK](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/tree/master/build) you can download.

> but i need to closeapp in case of disagree.

A fairly horrible user experience, but it that's what you want to do:

```
if (error.code === cordova.plugins.locationAccuracy.ERROR_USER_DISAGREED) {
    navigator.app.exitApp();
}
```

> and dont want to enable wifi as well

Enabling Wifi is entirely down to the Google API - this plugin has no control over the location settings request once it has been made.

**Comment by jammy525** [comment]
many thanks for giving your valuable time.
it helped me.thanks again:)
