### ISSUE TITLE
Location Accuracy Plugin , Nothing happens when I fire the function

### ISSUE THREAD

**Issue by lightyaer** [dpa99c/cordova-plugin-request-location-accuracy#41]
I built the following app and installed it on my phone, no errors anywhere..
but when I click on the button in Contacts Page, nothing happens, neither of the alerts are showing 
Please Advice.
Contacts.html
`<ion-header>
  <ion-navbar>
    <ion-title>
      Contact
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content>
  <ion-list>
    <ion-list-header>Follow us on Twitter</ion-list-header>
    <ion-item>
      <ion-icon name="ionic" item-start></ion-icon>
      @ionicframework
    </ion-item>

    <button ion-button (click)="enableLocation()" >Check Location Accuracy</button>

  </ion-list>
</ion-content>
`

Contacts.ts
`
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { LocationAccuracy } from '@ionic-native/location-accuracy';
import { AlertController } from 'ionic-angular/components/alert/alert-controller';

@Component({
  selector: 'page-contact',
  templateUrl: 'contact.html'
})
export class ContactPage {

  constructor(public navCtrl: NavController,
    private locationAccuracy: LocationAccuracy,
    private alertCtrl: AlertController) {

  }

  enableLocation() {
    this.locationAccuracy.canRequest().then((canRequest: boolean) => {

      if (canRequest) {
        let alert = this.alertCtrl.create({
          title: String(canRequest)
        })
        alert.present();
        // the accuracy option will be ignored by iOS
        this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(
          () => {
            let alert = this.alertCtrl.create({
              title: 'Request successful'
            })
            alert.present();
          },
          error => {
            let alert = this.alertCtrl.create({
              title: 'Error requesting location permissions' + JSON.stringify(error)
          })
        alert.present();
      }
        );
  }

});
  }
}
`

**Comment by dpa99c** [comment]
This code fragment alone is not sufficient information to diagnose any issue. 
Please do the following:

- specify exactly what platform/version you are testing and under what conditions.
- try connecting a remote debugger (Chrome Dev Tools/Safari Web Inspector) to the Cordova Webview of your app and placing breakpoints to step through the code at runtime.
- try building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) as a working reference as to how you should use this plugin.
- make sure you have read and understood the caveats and limitations of using this plugin in [its documentation](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/README.md).

**Comment by lightyaer** [comment]
Sorry, for the missing info, 
I am testing it on Android 8.0 OnePlus 3T, tested with mobile data and wifi, 
Yep, I'll try running the debugger and finding the bug, 
This itself is the example project, I wanted to integrate LocationAccuracy in my Main App where in I need to get Precise High Accuracy Coordinates when user goes on a specific page.
I think the caveats are related to ios devices only.

I hope this helps.

>     @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.0.2
    Node              : v6.9.5
    npm               : 3.10.10
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : c:\Android\sdk

Misc:

    backend : pro

**Comment by dpa99c** [comment]
Just re-tested the example project built with `cordova@8.0.0` and `cordova-android@7.0.0` running on Nexus 6P running Android 8.1 and it works fine.

**Comment by lightyaer** [comment]
Is your code same as mine? 
Did you ask for location permission via diagnostic plugin before making a request for accuracy? 
Did you test it for an Ionic project? 
Lastly, can you please share the example project you tested it on?

Thanks in Advance

**Comment by dpa99c** [comment]
> Is your code same as mine?
> Did you ask for location permission via diagnostic plugin before making a request for accuracy?
> Lastly, can you please share the example project you tested it on?

I tested it with [cordova-plugin-request-location-accuracy-example](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) which enables [requesting location authorization](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/android/js/index.js#L25) before [requesting location accuracy](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/android/js/index.js#L19).

> Did you test it for an Ionic project?

No. Ionic Native provides a [typescript wrapper](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/location-accuracy/index.ts) around this plugin which is created and maintained by the Ionic Team.
It is not a direct part of this plugin.
However, it is simply a wrapper and therefore shouldn't interefere with the underlying behaviour/logic of the plugin which it calls.

**Comment by lightyaer** [comment]
Solved it , Dissected each and every operation , from asking location permission to enabling high accuracy, 
turns out one doesnt need location permission,

Thanks alot for the help

**Comment by merlindasumardi** [comment]
hi @lightyaer , i have the same problem with you. can you help me to explain how you solved this problem? thank you

**Comment by lightyaer** [comment]
@merlindasumardi don't use canRequest, just ask for a request and try getting the location.. It'll work..

**Comment by Anujmoglix** [comment]
Location Plugin issue on MI Phone , It is giving location  without opening gps and going to true condition but giving issue on others phone

**Comment by kapilSoni101** [comment]
@lightyaer sir i have used location-accuracy plugin but i got every time canRequest will be 0.do you know why got return 0?

**Comment by dpa99c** [comment]
Please test with the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) to see if you can reproduce the issue to eliminate any issues in your own code.

**Comment by kapilSoni101** [comment]
@Anujmoglix  :sir i have used location-accuracy from below link:
https://ionicframework.com/docs/native/location-accuracy
If i used above i got cordova undefined i have already used before but why got 0
?
