### ISSUE TITLE
iOS settings redirection not working on 'resume' event

### ISSUE THREAD

**Issue by al06** [dpa99c/cordova-plugin-request-location-accuracy#44]
Great Plugin buddy, but in iOS settings redirection happens only on 'device ready' event.I need a functionality where user can't proceed in app if location is not ON so I want to call this code in 'resume' event as well as from some other files of my project.Is there a way.
Also Can we hide Cancel Button that appears in native dialog in iOS.
Any leads appreciated.

**Comment by dpa99c** [comment]
> in iOS settings redirection happens only on 'device ready' event.I need a functionality where user can't proceed in app if location is not ON so I want to call this code in 'resume' event as well as from some other files of my project.Is there a way.

Presumably "settings redirection" means you are calling [switchToSettings()](https://github.com/dpa99c/cordova-diagnostic-plugin#switchtosettings) of [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin). There is nothing preventing that function (or any of this plugin's functions) being called on resume.

> Also Can we hide Cancel Button that appears in native dialog in iOS.

No,  it's a native iOS dialog that cannot be customised.

> Any leads appreciated.

Next time please follow the issue template structure.
