### ISSUE TITLE
Plugin not working above android 6.0 and above

### ISSUE THREAD

**Issue by farazhere** [dpa99c/cordova-plugin-request-location-accuracy#45]
Hi, please help us in this issue, that the plugin works fine in android 4.x and 5.x but not on 6.0 and above?
What could be the reason?

**Comment by dpa99c** [comment]
Did you check if you have runtime permission to use location with `canRequest()` before calling `request()`?

If `canRequest()` returns false, you need to request runtime permission which you can do with [requestLocationAuthorization()](https://github.com/dpa99c/cordova-diagnostic-plugin#requestlocationauthorization) from [diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin).

Please use the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) as a working reference.

**Comment by farazhere** [comment]
ah alright let me check thanks..

**Comment by basitraza** [comment]
example project missing index.html

**Comment by basitraza** [comment]
any how i add the android platform and run in android then application crash

**Comment by dpa99c** [comment]
> example project missing index.html

The index.html is platform-specific so included via merges:

https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/android/index.html

https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/blob/master/merges/ios/index.html

**Comment by basitraza** [comment]
unfortunately stop

**Comment by dpa99c** [comment]
> unfortunately stop

You need to debug/fix your development environment - it build and runs fine in mine:

![screenshot_20180306-110001](https://user-images.githubusercontent.com/2345062/37029035-e2fd8912-212d-11e8-8f35-32b551bc2b82.png)

**Comment by basitraza** [comment]
build is successful in mine but application suddenly stop

**Comment by basitraza** [comment]
![capture](https://user-images.githubusercontent.com/37106715/37029213-6d518850-2158-11e8-9584-6653e8ba9417.PNG)

**Comment by basitraza** [comment]
Even the apk in the example project also stop

**Comment by dpa99c** [comment]
Are you running it on a device or emulator?

**Comment by basitraza** [comment]
device

**Comment by dpa99c** [comment]
It's possible the Play Services library is out-of-date or some other problem with it - you'll need to inspect the logcat output of the device to see what the exact error is. Or try another device.

**Comment by basitraza** [comment]
alright let me check

**Comment by dpa99c** [comment]
Can this be closed?

**Comment by dpa99c** [comment]
Closed due to no response from OP.
