### ISSUE TITLE
Build fails after adding this plugin

### ISSUE THREAD

**Issue by shirishparsekar** [dpa99c/cordova-plugin-request-location-accuracy#5]
I added this plugin using following command:
`cordova plugin add cordova-plugin-request-location-accuracy`

This is the error that I got when I tried building the app for android platform, after adding the plugin

> Running command: "C:\Program Files\nodejs\node.exe" c:\Apache24\htdocs\loc\hooks\after_prepare\010_add_platform_class.js c:\Apache24\htdocs\loc
> add to body class: platform-android
> ANDROID_HOME=C:\Users\shiri$h\AppData\Local\Android\android-sdk
> JAVA_HOME=C:\Program Files\java\jdk1.8.0_45
> No target specified, deploying to device '4810d66c'.
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   A problem occurred configuring root project 'android'.
>   Could not resolve all dependencies for configuration ':_debugCompile'.
>   Could not find any version that matches com.google.android.gms:play-services-location:+.
>    Searched in the following locations:
>        https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
>        https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
>        file:/C:/Users/shiri$h/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/maven-metadata.xml
>        file:/C:/Users/shiri$h/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-location/
>    Required by:
>        :android:unspecified
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 32.634 secs
> ERROR running one or more of the platforms: Error code 1 for command: cmd with args: /s,/c,"c:\Apache24\htdocs\loc\platforms\android\gradlew cdvBuildDebug -b c:\Apache24\htdocs\loc\platforms
> \android\build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
> You may not have the required environment or OS to run this project

I am using ionic-framework. When I do `ionic serve`, the project runs on the browser without any problems. I did some searching on google and found that many other people also had same issues but could not find any solution.

**Comment by dpa99c** [comment]
You need to install the "Google Repository" package under the "Extras" section in Android SDK Manager. I will update the plugin documentation to make this explicitly clear.

**Comment by shirishparsekar** [comment]
I installed Google Repository and it works fine now! Thanks for your immediate feedback!
