### ISSUE TITLE
Build failed...

### ISSUE THREAD

**Issue by pyeonjaesik** [dpa99c/cordova-plugin-request-location-accuracy#51]
If I install cordova-plugin-fcm additionally, build err occur. Following is my err
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Comment by dpa99c** [comment]
See #50 - the cause is the same: conflicting versions of Firebase library specified in Gradle config

**Comment by dpa99c** [comment]
I've updated [the plugin documentation](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#android-build-issues) to make this clear.

**Comment by pyeonjaesik** [comment]
I tried.
cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=15.+
cordova plugin add cordova-android-firebase-gradle-release --variable FIREBASE_VERSION=15.+

But not working

**Comment by dpa99c** [comment]
"not working" is not sufficient information to help you.

If you'd like further assistance, please post the full build log containing the error message, list of plugins+versions in your Cordova project, version of cordova-android, and any other useful information.

The [issue template](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/.github/ISSUE_TEMPLATE.md) provides a structure for providing this information.

**Comment by pyeonjaesik** [comment]
Sorry.
my list of plugins 
    "cordova-android": "^7.0.0",
    "cordova-android-firebase-gradle-release": "^1.0.0",
    "cordova-android-play-services-gradle-release": "^1.4.1",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-fcm": "^2.1.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-intent": "git+https://github.com/napolitano/cordova-plugin-intent.git",
    "cordova-plugin-request-location-accuracy": "^2.2.3",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova.plugins.diagnostic": "^4.0.6"

And I still got the above err

Execution failed for task ':app:processDebugGoogleServices'.
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Comment by pyeonjaesik** [comment]
I'm submitting a ... (check one with "x"):

 bug report
 feature request
 documentation issue
Bug report
Current behavior:

Expected behavior:

Steps to reproduce:

Environment information

Cordova CLI version
8.0.0
Cordova platform version
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
Plugins & versions installed in project (including this plugin)
com.napolitano.cordova.plugin.intent 0.1.3 "IntentPlugin"
cordova-android-firebase-gradle-release 1.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 1.4.1 "cordova-android-play-services-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.6 "Diagnostic"
Dev machine OS and version, e.g.
Windows 10
Runtime issue

Device details
galaxy A7
OS details
e.g. iOS 11.2, Android 8.1
Android build issue:

Node JS version
v6.11.4

Gradle version
ls platforms/android/.gradle
Target Android SDK version
android:targetSdkVersion in AndroidManifest.xml
Android SDK details
sdkmanager --list | sed -e '/Available Packages/q'
iOS build issue:

Node JS version
node -v
XCode version
If using an Ionic Native Typescript wrapper for this plugin:

Ionic environment info
ionic info
Installed Ionic Native modules and versions
npm list | grep "@ionic-native"
Related code:

insert any relevant code here such as plugin API calls / input parameters
Console output

console output


Other information:

Feature request
Documentation issue

**Comment by cquezpro** [comment]
Hi @dpa99c 
I got same error today. please help me.
thanks
