### ISSUE TITLE
Location Accuracy Plugin Nothing happens when I fire the function

### ISSUE THREAD

**Issue by Ramakrishna1064** [dpa99c/cordova-plugin-request-location-accuracy#55]
I built the following code in my phone,no errors anywhere,But when I click on the button i need to check either device location enable or not but using below code nothing happens i am using android 7.0 version can some one help me please and i just follow this link How to programatically enable and disable GPS in Ionic Framework or Cordova

  start(){

        this.locationAccuracy.canRequest().then((canRequest: boolean) => {
          if(canRequest) {
            this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(() => {
                console.log('Request successful.')
              },
              error => {
                console.log('Error requesting location permissions', error)
              }
            );
          }
        });
      }

**Comment by dpa99c** [comment]
Have you ensure the app has location authorisation before calling the code above?

Please read the documentation, in particular see the [Full Android & iOS example](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#full-android--ios-example) section. 

Also try building+running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) to understand functionality of the plugin.

Please ask any further support questions on the Ionic Forums or Stackoverflow

**Comment by Ramakrishna1064** [comment]
I am using  https://ionicframework.com/docs/native/location-accuracy/ is this not working ?,If not what is the use of this plugin?

**Comment by dpa99c** [comment]
Ionic Native just provides a Typescript wrapper around the JS API of this Cordova plugin.

If you have an issue with the Ionic Native Typescript wrapper, raise it against [Ionic Native](https://github.com/ionic-team/ionic-native/).

**Comment by Ramakrishna1064** [comment]
https://ampersandacademy.com/tutorials/ionic-framework-version-2/location-enable-request-using-the-location-accuracy-plugin what about this?

**Comment by Ramakrishna1064** [comment]
So finally is there no code for resolve my issue?

**Comment by dpa99c** [comment]
Github issues are for reporting bugs or requesting features, not asking for help/support.

Ask on the [Ionic Forum](https://forum.ionicframework.com/)  or StackOverflow.
