### ISSUE TITLE
Android 7: Plugin does not work if location services are already turned on

### ISSUE THREAD

**Issue by juliabat** [dpa99c/cordova-plugin-request-location-accuracy#62]
Hi 
I testing out the plugin with the [prebuildt example apk](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example/tree/master/build).

 The plugin works like a dream if location services are off: it activates location services and changes accuracy. 

However if location services are **on**, error code 4 is always returned in the error callback. 
I get the error on both of my test devices: 
OS: Android 7
Device: OnePlus 3T and Samsung Galaxy S8

Cheers :)

**Comment by dpa99c** [comment]
Sounds like the same issue as #61 - i.e. pressing "OK" invokes the error callback with code 4 (same as if user presses "No, thanks") instead of the success callback. It's caused by a bug in the latest version of the Play Services library.
