### ISSUE TITLE
Not working in Ionic 3

### ISSUE THREAD

**Issue by borjalo** [dpa99c/cordova-plugin-request-location-accuracy#64]
I'm trying to use it in an Ionic 3 application, but it does not enter the function.

```
this.locationAccuracy.canRequest().then((canRequest: boolean) => {
        if (canRequest) {

          // the accuracy option will be ignored by iOS
          this.locationAccuracy.request(this.locationAccuracy.REQUEST_PRIORITY_HIGH_ACCURACY).then(

            // If request succesful
            () => {
```

**Comment by dpa99c** [comment]
Please use the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) for a known working reference of how to use the plugin.

If your issue explicitly relates to the [Ionic Native Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/location-accuracy/index.ts) then please raise the [issue against Ionic Native](https://github.com/ionic-team/ionic-native/issues).
