### ISSUE TITLE
Conflicts with google plus signin

### ISSUE THREAD

**Issue by hsjeevan** [dpa99c/cordova-plugin-request-location-accuracy#65]

**Comment by hsjeevan** [comment]
Google plus sign-in stops working after installing the location-accuracy plugin. 

I'm using AndroidPermissions, Geolocation, NativeGeocoder, and LocationAccuracy plugins for one of my ionic apps and google signin doesnt work when LocationAccuracy plugin is installed.

any help will be appreciated.

**Comment by dpa99c** [comment]
This plugin [specifies `com.google.android.gms:play-services-location:15.+`](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/blob/master/plugin.xml#L32) as a library dependency so it's likely a versioning problem with the Play Services Library.

I should probably add a plugin variable to allow the default version (currently `15.+`) to be overridden on plugin installation. You'd still need to know what version the other plugins were specifying to ensure they match.

In the meantime you could try installing [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release) into the project which will allow you to override the Play Services version specified by this plugin.

**Comment by dpa99c** [comment]
This has been resolved in v2.3.0 of this plugin which enables you to specify a custom version of the Play Services Location library component on which the plugin depends. 

See [Play Services version](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#play-services-version) section in the documentation for details.
