### ISSUE TITLE
Version conflict with FCM plugin

### ISSUE THREAD

**Issue by praveen5exceptions** [dpa99c/cordova-plugin-request-location-accuracy#66]
When using location-accuracy plugin with ionic FCM or Ionic Push this error comes, i try to change google-service version manually but nothing fixed.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.+.

**Comment by dpa99c** [comment]
This has been resolved in v2.3.0 of this plugin which enables you to specify a custom version of the Play Services Location library component on which the plugin depends. 

See [Play Services version](https://github.com/dpa99c/cordova-plugin-request-location-accuracy#play-services-version) section in the documentation for details.
