### ISSUE TITLE
[Question] Is possible to do something like this?

### ISSUE THREAD

**Issue by guillenotfound** [dpa99c/cordova-plugin-request-location-accuracy#7]
Hello!

I would like to know if is possible to display an alert like this to just enable GPS with default user config, instead of trying to modify user's permissions.

![image](https://cloud.githubusercontent.com/assets/5492960/15854992/25c3ecea-2cad-11e6-9954-78133dfdc8e4.png)

**Comment by dpa99c** [comment]
Short answer: no

Long answer: The dialog that is displayed is a native dialog created by the Google Play Services library. On Android, when it comes to Location Mode, there is no concept of "default user config", there is simply the four different Location Modes: Off, Battery Saving (network only), Device Only (gps only) and High Accuracy (network and gps).

What this plugin does is allow you to request a Location Mode with increased accuracy from directly within your app using the Google Play Services library. The dialog that is displayed is invoked by Google Play Services and therefore it is not possible to customise it.
