### ISSUE TITLE
Feature Request: create custom messages for native prompt

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-request-location-accuracy#71]
1) Is it possible to add or alter the displayed message in the native prompt for both Android and iOS?  
2) Is there any way to auto-expand the Android prompt to show the full message?

I read through the docs and didn't see any method but I know its possible with `diagnostics` so I thought I would ask.  Would be a nice feature to be able to further explain to the use why GPS permission is being requested.

**Comment by dpa99c** [comment]
Unfortunately in this case, for both Android and iOS, the native dialogs are auto-generated by the operating system so there is no opportunity to customize them.
